# Generated by Django 3.0.5 on 2020-05-13 07:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('akun', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Karyawan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('npk', models.CharField(max_length=9)),
                ('nik', models.CharField(max_length=16)),
                ('tgl_lhr', models.DateField()),
                ('gol_darah', models.IntegerField(choices=[(1, 'A'), (2, 'B'), (3, 'AB'), (4, 'O')])),
                ('alamat', models.TextField(max_length=300)),
                ('karyawan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='akun.Profil')),
            ],
        ),
        migrations.CreateModel(
            name='Keluarga',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(choices=[(1, 'Menikah'), (2, 'Belum Menikah')])),
                ('nama_istri', models.CharField(blank=True, max_length=50, null=True)),
                ('tgl_lhr', models.DateField(blank=True, null=True)),
                ('anak_1', models.CharField(blank=True, max_length=50, null=True)),
                ('tgl_lhr_1', models.DateField()),
                ('anak_2', models.CharField(blank=True, max_length=50, null=True)),
                ('tgl_lhr_2', models.DateField()),
                ('k_karyawan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='human_capital.Karyawan')),
            ],
        ),
        migrations.CreateModel(
            name='Karir',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_karir', models.IntegerField(choices=[(1, 'Permanent'), (2, 'Unpermanent')])),
                ('tgl_efektif', models.DateField()),
                ('job_desk', models.IntegerField(choices=[(1, ((1, 'Kabid Kepesertaan'), (2, 'Kabid Pelayanan')))])),
                ('unit_kerja', models.CharField(max_length=30)),
                ('karyawan_k', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='human_capital.Karyawan')),
            ],
        ),
    ]
