# Generated by Django 3.0.5 on 2020-08-27 05:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('akun', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='bidang',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='jenis_aset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Office',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Operator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=50)),
                ('perusahaan', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Pemeliharaan_Hardware',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dead_pixel_monitor', models.BooleanField(blank=True, choices=[(0, 'TIDAK'), (1, 'YA')], default=False, null=True)),
                ('keyboard_mouse', models.BooleanField(blank=True, choices=[(0, 'TIDAK'), (1, 'YA')], default=False, null=True)),
                ('cacat_casing', models.BooleanField(blank=True, choices=[(0, 'TIDAK'), (1, 'YA')], default=False, null=True)),
                ('fungsi_cooler_fan', models.BooleanField(blank=True, choices=[(0, 'TIDAK'), (1, 'YA')], default=False, null=True)),
                ('pembersihan_casing', models.BooleanField(blank=True, choices=[(0, 'TIDAK'), (1, 'YA')], default=False, null=True)),
                ('cleaning_cooler_fan', models.BooleanField(blank=True, choices=[(0, 'TIDAK'), (1, 'YA')], default=False, null=True)),
                ('merapikan_kabel', models.BooleanField(blank=True, choices=[(0, 'TIDAK'), (1, 'YA')], default=False, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Pemeliharaan_Keamanaan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('update_antivirus', models.BooleanField(blank=True, choices=[(0, 'TIDAK'), (1, 'YA')], default=False, null=True)),
                ('full_scanning', models.BooleanField(blank=True, choices=[(0, 'TIDAK'), (1, 'YA')], default=False, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Pemeliharaan_Software',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disk_cleanup', models.BooleanField(blank=True, choices=[(0, 'TIDAK'), (1, 'YA')], default=False, null=True)),
                ('disk_defragment', models.BooleanField(blank=True, choices=[(0, 'TIDAK'), (1, 'YA')], default=False, null=True)),
                ('uinstall_app_tdk_perlu', models.BooleanField(blank=True, choices=[(0, 'TIDAK'), (1, 'YA')], default=False, null=True)),
                ('restart_pc', models.BooleanField(blank=True, choices=[(0, 'TIDAK'), (1, 'YA')], default=False, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Pemeliharaan_Umum',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rescure_disc', models.BooleanField(blank=True, choices=[(0, 'TIDAK'), (1, 'YA')], default=False, null=True)),
                ('update_windows', models.BooleanField(blank=True, choices=[(0, 'TIDAK'), (1, 'YA')], default=False, null=True)),
                ('clear_browser_cache', models.BooleanField(blank=True, choices=[(0, 'TIDAK'), (1, 'YA')], default=False, null=True)),
                ('cek_ruangan_hdd', models.BooleanField(blank=True, choices=[(0, 'TIDAK'), (1, 'YA')], default=False, null=True)),
                ('cek_konfigurasi_startup', models.BooleanField(blank=True, choices=[(0, 'TIDAK'), (1, 'YA')], default=False, null=True)),
                ('kosongkan_recycle_bin', models.BooleanField(blank=True, choices=[(0, 'TIDAK'), (1, 'YA')], default=False, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Sistem_Operasi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Aset_IT',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no_reg', models.CharField(max_length=16, verbose_name='NO REGISTER')),
                ('merk_type', models.CharField(max_length=100, verbose_name='MERK/TYPE')),
                ('serial_num', models.CharField(max_length=50, verbose_name='SERIAL NUMBER')),
                ('tahun_pengadaan', models.DateField(verbose_name='TAHUN PENGADAAN')),
                ('ip_addr', models.GenericIPAddressField(verbose_name='IP ADDRESS')),
                ('lisensi_os', models.CharField(max_length=70, verbose_name='LISENSI OS')),
                ('lisensi_office', models.CharField(max_length=64, verbose_name='LISENSI OFFICE')),
                ('ocs_inventory', models.BooleanField(choices=[(0, 'TIDAK'), (1, 'YA')], default=False, verbose_name='OCS INVENTORY')),
                ('mac_address', models.CharField(blank=True, max_length=17, null=True)),
                ('maintenance_done', models.DateField(blank=True, null=True, verbose_name='MAINTENANCE I')),
                ('maintenance_next', models.DateField(blank=True, null=True, verbose_name='MAINTENANCE II')),
                ('timestamp', models.DateField(auto_now_add=True)),
                ('bidang', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventaris_apps.bidang', verbose_name='BIDANG/BAGIAN')),
                ('jenis_aset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventaris_apps.jenis_aset', verbose_name='JENIS ASET')),
                ('nama_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='akun.Profil', verbose_name='PENGGUNA')),
                ('office', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventaris_apps.Office', verbose_name='OFFICE')),
                ('operasi_sistem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventaris_apps.Sistem_Operasi', verbose_name='SISTEM OPERASI')),
                ('operator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventaris_apps.Operator')),
                ('pemeliharaan_hardware', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventaris_apps.Pemeliharaan_Hardware')),
                ('pemeliharaan_keamanan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventaris_apps.Pemeliharaan_Keamanaan')),
                ('pemeliharaan_software', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventaris_apps.Pemeliharaan_Software')),
                ('pemeliharaan_umum', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventaris_apps.Pemeliharaan_Umum')),
            ],
        ),
    ]
