# Generated by Django 3.0.5 on 2020-07-25 05:44

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JenisPekerjaan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kode', models.CharField(max_length=4)),
                ('nama_pekerjaan', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='LokasiPekerjaan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kode', models.CharField(max_length=4)),
                ('nama_kota', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='daftar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nik', models.CharField(max_length=16)),
                ('nama', models.CharField(max_length=50)),
                ('tgl_lahir', models.DateField(default=django.utils.timezone.now)),
                ('no_hp', models.CharField(max_length=13)),
                ('surel', models.EmailField(blank=True, max_length=254, null=True)),
                ('upah', models.IntegerField()),
                ('kode_paket', models.CharField(choices=[('T', 'JKK,JKM'), ('L', 'JKK,JKM,JHT')], max_length=1)),
                ('kode_iuran', models.IntegerField(choices=[(1, '1 BLN'), (3, '3 BLN'), (6, '6 BLN'), (12, '12 BLN')])),
                ('time_stamp', models.DateTimeField(auto_now_add=True)),
                ('jenis_pekerjaan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='winback.JenisPekerjaan')),
                ('jenis_pekerjaan2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='jenis2', to='winback.JenisPekerjaan')),
                ('lokasi_pekerjaan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='winback.LokasiPekerjaan')),
            ],
        ),
    ]
