# Generated by Django 3.0.5 on 2020-06-15 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Antol',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kode', models.IntegerField()),
                ('kpj', models.CharField(max_length=11)),
                ('nik', models.CharField(max_length=16)),
                ('nama', models.CharField(max_length=50)),
                ('no_hp', models.CharField(max_length=13)),
                ('email', models.EmailField(max_length=254)),
                ('shift', models.CharField(max_length=20)),
                ('kegiatan', models.CharField(max_length=10)),
                ('tgl_antol', models.DateField()),
            ],
        ),
    ]
